apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: prod-subnet-1
spec:
  forProvider:
    region: us-east-2
    #availabilityZone: us-east-2a
    cidrBlock: 192.168.1.0/24
    vpcIdRef:
      name: production-vpc
    tags:
    - key: Environment
      value: Production
    - key: Name
      value: prod-subnet-1
    - key: Owner
      value: Oldspeech
    - key: kubernetes.io/cluster/challengeaws-cluster
      value: shared
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: default

---

apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: prod-subnet-2
spec:
  forProvider:
    region: us-east-2
    #availabilityZone: us-east-2b
    cidrBlock: 192.168.2.0/24
    vpcIdRef:
      name: production-vpc
    tags:
    - key: Environment
      value: Production
    - key: Name
      value: prod-subnet-2
    - key: Owner
      value: Oldspeech
    - key: kubernetes.io/cluster/challengeaws-cluster
      value: shared
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: default

---

apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: prod-subnet-3
spec:
  forProvider:
    region: us-east-2
    availabilityZone: us-east-2b
    cidrBlock: 192.168.3.0/24
    vpcIdRef:
      name: production-vpc
    tags:
    - key: Environment
      value: Production
    - key: Name
      value: prod-subnet-3
    - key: Owner
      value: Oldspeech
    - key: kubernetes.io/cluster/challengeaws-cluster
      value: shared
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: default